### PR TITLE
Fixed two bugs.

### PR DESCRIPTION
**Pull request by ShaneQi**
#### Bug 1

`setStatusBarHidden(_:with:)` was deprecated, causing `LightboxConfig.hideStatusBar = true` not work.

**Fix:** switched to `prefersStatusBarHidden` property to implement it.

#### Bug 2

When infoLabel's `fullText` is empty, the footer doesn't remove gradient layer properly.  
Gradient layer should be removed from footer view if infoLabel's fullText is empty, regardless of expanded state.

**Fix:** added `infoLabel.fullText.isEmpty` check in FooterView InfoLabelDelegate extension.

### CODE REVIEW

**Comment by ShaneQi** [comment]
I don't know why my PR didn't pass CI. It seems like the CI env's problem but not my commits.

**Comment by r-mckay** [comment]
Hello @ShaneQi!
The CI configuration has been updated and should now run your PR properly.

**Comment by ShaneQi** [comment]
@r-mckay 
Thanks for informing me. I've made CI check this PR again.

**Comment by zenangst** [comment]
@ShaneQi thanks for the PR, keep rockin! :drum

**Comment by philZF** [comment]
Hi, it's not working on iOS12...

**Pull request merged**
