### PR TITLE
Updating the .image property of a LightboxImage instance after Lightbox has downloaded an image via URL

### PR DESCRIPTION
**Pull request by vitalii-tym**
This change allows apps to access the images inside LightboxImage even if those images were downloaded from an external URL provided by the app.
Can be useful, for example, when an app needs to provide sharing functionality.
See example of such a usage in https://github.com/hyperoslo/Lightbox/issues/98

### CODE REVIEW

**Comment by onmyway133** [comment]
@vitalii-tym Hi, thanks for your PR. This is good addition. What do you think about when user opens and closes Lightbox in a short time, so that it still hasn't finished downloading all the images?

**Comment by vitalii-tym** [comment]
The .image property is still going to be nil in that case (as it always was before).
The apps using Lightbox should mind that .image is optional and safely unwrap it.
In my example at https://github.com/hyperoslo/Lightbox/issues/98 tapping such a Share button would simply do nothing.
Ideally the Delete button (which is used for Share functionality in the example) is supposed to be disabled while image is still being loaded by Lightbox, but its state is always enabled.

**Comment by vitalii-tym** [comment]
@onmyway133 I took a second look and found that there was indeed a strong capture of self. Fixed now. Thanks for the heads up.

**Comment by vitalii-tym** [comment]
sorry, too much commits in here now. Made another PR with only one concrete commit here https://github.com/hyperoslo/Lightbox/pull/122

**Pull request closed without merging**
