### PR TITLE
Fix app crash when tap delete button.

### PR DESCRIPTION
**Pull request by alexandrgl**
Fix app crash when tap delete button.

### CODE REVIEW

**Comment by alexandrgl** [comment]
The connected issue: https://github.com/hyperoslo/Lightbox/issues/213

**Comment by alexandrgl** [comment]
@3lvis 
Hi!
Could you help me to merge this pull request?
I'm a bit confused. I thought I should to assign someone for review but I have not such option.
It would be nice to fix this crash.
Thank you!

**Comment by 3lvis** [comment]
Added! Let me know if it resolves the issue.

**Comment by alexandrgl** [comment]
Yes, it resolves crash. The delete feature works perfectly now.
Thanks a lot!

**Pull request merged**
