### PR TITLE
Added possibility to set image preload value

### PR DESCRIPTION
**Pull request by t0a0**
I tried to load the LightboxController with hundreds of images, and ran into memory issues.

As of now, Lightbox loads all the passed images at once, creating a memory usage spike for a high amount of images. Also it keeps all of them in memory, which is not optimal for large numbers of images. 

Therefore, it might be useful to have a possibility to set a number of images, which the user will have loaded at a time.
I implemented it in this PR. 

So if preload = 0, we load all the images (default behavior), if it equals to 2, we load:
-**2**, -**1**, **0**(current image), **1**, **2**.

### CODE REVIEW

**Comment by mehulmodihb** [comment]
Hello,

Is this pull request is merged or not?

**Comment by zenangst** [comment]
ping @vadymmarkov @onmyway133 :)

**Comment by onmyway133** [comment]
@t0a0 @Schaefers Hi, sorry for the delay. This looks good to us. Thanks a  lot for the PR 🚀

**Comment by kundanjadhav** [comment]
swiping images create memory spike. again facing same problem. Images are stored in memory.

Please help

**Comment by dknchris** [comment]
Am I doing something wrong? The image memory is not being deallocated. Generally, there should be a recycling option or something and allow us to deallocate memory for images that the user has swiped away.

**Pull request merged**
