### PR TITLE
Feature - Real interactive transition

### PR DESCRIPTION
**Pull request by RamonGilabert**
This guy!

- The transition now is 100% interactive, so it'll show the screen behind the screen animating, right now it was showing just a white screen.
- Bonus: the scroll thing so many said, it's fixed! :yum: 

app

### CODE REVIEW

**Comment by RamonGilabert** [comment]
Right when it's merged, I'll have to change some stuff in the client project I think! :)

**Comment by RamonGilabert** [comment]
app

**Comment by richardoti** [comment]
hemip0s
No bugz detected

**Comment by 3lvis** [comment]
It was merged, so it should.

**Comment by 3lvis** [comment]
Newest version is https://github.com/hyperoslo/Lightbox/releases/tag/2.5.1

**Comment by 3lvis** [comment]
Hi, 

That's because I haven't updated the CocoaPod, I don't have the necessary rights to do it. You can point straight to master, that should do the trick.

**Pull request merged**
