### PR TITLE
Hide controls upon single tap

### PR DESCRIPTION
**Pull request by onmyway133**
- Add single tap gesture recognizer
- It takes a small delay (around 0.2 second) for the single tap to be recognized, because the iOS needs to wait a bit to determine if there should be double tap. This is also the case in Facebook app

### CODE REVIEW

**Comment by zenangst** [comment]
Why are the tests failing?

**Comment by zenangst** [comment]
Or more like, Travis can't build the thing

**Comment by onmyway133** [comment]
@zenangst yay, travis is happy again

**Comment by zenangst** [comment]
@onmyway133 fantastic! ⭐️

**Comment by onmyway133** [comment]
🏂

**Pull request merged**
